version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-lit
    ports:
      - '80:80'
    volumes:
      - ./api/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: api
      target: test-build-stage
      dockerfile: Dockerfile
    container_name: server-lit
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg-lit-test
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: test
    volumes:
      - 'test_data:/bitnami/postgresql'
    ports:
      - '5432:5432'
    networks:
      - backend
  
  blog:
    build:
      context: client
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: client-lit
    ports:
      - '8000:8000'
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  test_data:
    driver: local
